name: Releases

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@cycling-market"

      - run: npm install
      - run: npm pack

      - uses: Klemensas/action-autotag@stable
        id: update_tag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"

      - name: Create and upload Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: steps.update_tag.outputs.tagname
        with:
          tag_name: ${{ steps.update_tag.outputs.tagname }}
          name: ${{ steps.update_tag.outputs.tagname }}
          generate_release_notes: true
          files: "cycling-market-tinkoff-payment-sdk-${{steps.update_tag.outputs.version}}.tgz"

      - run: npm publish
        if: steps.update_tag.outputs.tagname
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [master]
